add more verbose error handling
Levminer/trusted-signing-cli pull request #4
Opened 2024-10-09 08:14 UTC by don41382

Thanks Levminer for helpful project. I had trouble getting the signing to work, so I decided to add more verbose error handling, which helped me to pin down the error.

2024-10-09 15:53 UTC, Levminer requested changes

2024-10-09 15:53 UTC, Levminer commented on src/main.rs
> +use std::ffi::OsString;
This import is unused

2024-10-10 12:36 UTC, Levminer approved these changes
Thanks!

2024-10-10 12:37 UTC, merged

2024-10-10 12:44 UTC, don41382 commented
Thanks for making the first step in creating this project!